---
apiVersion: api.cerbos.dev/v1
description: Policy for settings resource
resourcePolicy:
  version: "default"
  importDerivedRoles:
    - common_roles
  resource: "settings"
  rules:
    # Admin rules - full access within their organization
    - actions: ['*']
      effect: EFFECT_ALLOW
      roles:
        - admin
      derivedRoles:
        - organization_admin

    # Guest rules - no access
    - actions: ['*']
      effect: EFFECT_DENY
      roles:
        - guest