---
server:
  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"

storage:
  driver: "disk"
  disk:
    directory: /policies
    watchForChanges: true

audit:
  enabled: true
  backend: local
  local:
    storagePath: /tmp/cerbos/audit.log

schema:
  enforcement: reject