name: Bug Report
description: Report a bug in the Sports Management App
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thanks for reporting a bug! Please provide detailed information to help us resolve it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug in detail...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did this bug occur?
      options:
        - Development (local)
        - Staging
        - Production
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application?
      options:
        - Frontend (React/Next.js)
        - Backend (Node.js/Express)
        - Database (PostgreSQL)
        - Authentication
        - Game Management
        - Referee Management
        - Assignment System
        - Calendar/Scheduling
        - Other

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (minor issue, workaround available)
        - Medium (affects functionality but not critical)
        - High (major functionality broken)
        - Critical (application unusable, data loss)
    validations:
      required: true

  - type: textarea
    id: error_logs
    attributes:
      label: Error Messages/Logs
      description: Include any error messages, console logs, or stack traces
      placeholder: Paste error messages here...
      render: shell

  - type: textarea
    id: browser_info
    attributes:
      label: Browser/Environment Info
      description: Browser version, OS, Node.js version, etc.
      placeholder: |
        - Browser: Chrome 120.0.0.0
        - OS: macOS 14.0
        - Node.js: 18.17.0
        - Database: PostgreSQL 14

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Screenshots, related issues, recent changes, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided clear steps to reproduce the issue
          required: true
        - label: I have included relevant error messages or logs
          required: false
        - label: I have tested this in the latest version
          required: false