steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/sports-management-backend:latest',
      './backend'
    ]

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sports-management-backend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'sports-management-backend',
      '--image', 'gcr.io/$PROJECT_ID/sports-management-backend:latest',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '3001',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-cloudsql-instances', '$PROJECT_ID:us-central1:sports-management-db',
      '--set-env-vars', 'NODE_ENV=production',
      '--set-secrets', 'DATABASE_URL=database-url:latest,JWT_SECRET=jwt-secret:latest',
      '--timeout', '300'
    ]

options:
  logging: CLOUD_LOGGING_ONLY