version: "3.8"

services:
  # Development Backend API Server
  backend-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: dev
    container_name: sportsmanager-backend-dev
    environment:
      NODE_ENV: development
      PORT: 3002

      # Database - shared with production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sports_management_dev
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/sports_management_dev

      # JWT
      JWT_SECRET: dev-secret-key-not-for-production
      JWT_EXPIRES_IN: 7d

      # Cerbos - shared with production
      CERBOS_HOST: cerbos:3593
      CERBOS_TLS: false
      CERBOS_CACHE_ENABLED: true
      CERBOS_CACHE_TTL: 300000

      # Auth Bypass for Development/Figma
      DISABLE_AUTH: true

      # Redis
      DISABLE_REDIS: true

      # CORS Configuration
      FRONTEND_URL: https://dev.syncedsport.com
      PRODUCTION_DOMAINS: https://dev.syncedsport.com,https://dev.cpsc405.joeyfishertech.com,http://localhost:3005

      # Rate Limiting
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 1000

    ports:
      - "3002:3002"
    # Note: postgres and cerbos are in external docker-compose.deploy.yml
    # depends_on only works within the same compose file
    restart: unless-stopped
    networks:
      - sportsmanager-network

  # Development Frontend Next.js Application
  frontend-dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: dev
    container_name: sportsmanager-frontend-dev
    environment:
      NODE_ENV: development
      PORT: 3005

      # API Configuration
      NEXT_PUBLIC_API_URL: https://dev.syncedsport.com/api
      NEXT_PUBLIC_API_BASE_URL: https://dev.syncedsport.com/api

      # Environment
      NEXT_PUBLIC_ENV: development

      # Auth Bypass for Development/Figma
      NEXT_PUBLIC_DISABLE_AUTH: true

      # Features
      NEXT_PUBLIC_ENABLE_DEBUG: true

      # Maps
      NEXT_PUBLIC_OPENROUTE_API_KEY: eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjQyZTg3ZTU0NWQ0NzQ5OWY4MWQ0MmZkYmMyZjNhM2YwIiwiaCI6Im11cm11cjY0In0=

      NEXT_TELEMETRY_DISABLED: 1

    ports:
      - "3005:3005"
    depends_on:
      - backend-dev
    restart: unless-stopped
    networks:
      - sportsmanager-network

networks:
  sportsmanager-network:
    external: true

